fix: add label(s) without success comment if successComment is false
semantic-release/github pull request #532
Opened 2022-07-31 06:59 UTC by June21x

Currently the `successComment` and `releasedLabels`  behaviour are not decoupled.
My team is currently using this and wish to label each released issue with latest release version, so that we could filter out issues based on release version on the labels when working with GitHub's Project V2 automation workflow.

However, the `successComment` on multiple issues will trigger a lot of emails and GitHub Teams App notifications, which we would like to turn off to avoid annoying notification spamming.

This PR removes the coupling between `successComment` and `releasedLabels`, so that user could feel free to add labels without the bot comments.

close #421

2022-08-02 03:28 UTC, June21x commented
@gr2m Please review

2022-08-29 01:49 UTC, zigang93 approved these changes

2022-08-29 18:43 UTC, gr2m requested changes
can you please add a test that verifies the new behavior? Otherwise we risk a future regression

2022-09-12 04:42 UTC, closed without merging

2022-09-12 04:47 UTC, june21x commented
thanks for the review @zigang93 @gr2m, I will create another clean PR for this (with updated test) soon since I noticed that I didn't follow the current Prettier rule and there were also irrelevant changes in package.json